# Generated by Django 3.0.7 on 2020-08-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200823_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/%Y%m%d'),
        ),
    ]
