# Generated by Django 3.0.7 on 2020-08-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_remove_article_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
